### ISSUE TITLE
description/context gathering checklist

### ISSUE THREAD

**Issue by cathydeng** [smartchicago/chicago-atlas#211]
@KylaWilliams @smarziano here's a checklist of all of the descriptions we've agreed to collect & add to the site. Can you provide the following, to be added to the health atlas?

on hospital page:
- [x] definition of what 'service category' means, how they are defined, descriptions of service categories
- [x] description of what medical surgical admissions are & why they are singled out as a service category
- [x] description for the finance summary chart, including a definition of what charity care is
- [x] description for the revenue source chart, including context of private vs public source
- [x] description of inpatient vs outpatient (#200)

on zip code place page
- [x] description for the injuries chart, including explanation of why it is only for outpatient admissions & how the injury sub-categories are defined
- [x] clarification/descriptions for the injury sub-categories

miscellaneous stuff, referenced in other issues
- [x] description of JSON (#194)
- [x] Purple Binder data sources (#209)
- [x] description for hospital listing page http://chicago-atlas-staging.herokuapp.com/hospitals (#205)
